### ISSUE TITLE
Code suggestion: use filepath.Join()

### ISSUE THREAD

**Issue by joonas-fi** [shimmeringbee/controller#10]
Am not sure if you're open to code suggestions, so just close this if not!

I noticed manual path-building in [many places](https://github.com/shimmeringbee/controller/search?q=os.PathSeparator) like this:
https://github.com/shimmeringbee/controller/blob/2899d6d1972830c69ce5e62729eed77143ec4dc5/main.go#L28

There's a cleaner, semantic and OS-agnostic way to do it with: [filepath.Join()](https://godoc.org/path/filepath#Join)

**Comment by pwood** [comment]
Thanks for the suggestion @joonas-fi - somehow had missed the native Go file joining. The paths I'd been generating on Windows and Linux (I dev on Windows, run my network on Linux) had been right, but much nicer to use the correct function.
